FROM nginx

COPY ./Web /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./startup.sh /docker-entrypoint.d/startup.sh

# Expose port 80 (default for HTTP)
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]